version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    build:
          context: ./db
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_DATABASE_EMAIL=${MYSQL_DATABASE_EMAIL}
              - MYSQL_DATABASE_ONEPUSH=${MYSQL_DATABASE_ONEPUSH}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    command: --innodb-use-native-aio=0
    volumes:
          - "./db/db/:/var/lib/mysql"
    networks:
      - new
  nestjs:
    container_name: nestjs
    depends_on:
      - db
    stdin_open: true
    links:
      - db
    build: 
          context: ./back-main
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
            - 3200:3200
    networks:
      - new
  # sms:
  #   container_name: sms
  #   depends_on:
  #     - db
  #   build: 
  #         context: ./microservices/notification/sms
  #         args:
  #             - MYSQL_DATABASE=${MYSQL_DATABASE}
  #             - MYSQL_USER=${MYSQL_USER}
  #             - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #             - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   ports:
  #           - 3300:3200
  #   networks:
  #     - new
  email:
    container_name: email
    depends_on:
      - db
    build: 
          context: ./microservices/notification/email
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
            - 3400:3400
    networks:
      - new
  onepush:
    container_name: onepush
    depends_on:
      - db
    build: 
          context: ./microservices/notification/onepush
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
            - 3600:3600
    networks:
      - new
  facebook:
    container_name: facebook
    depends_on:
      - db
    build: 
          context: ./microservices/social/facebook
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
            - 3700:3700
    networks:
      - new
  instagram:
    container_name: instagram
    depends_on:
      - db
    build: 
          context: ./microservices/social/instagram
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3800:3800
    networks:
      - new

  cielo:
    container_name: cielo
    depends_on:
      - db
    build: 
          context: ./microservices/payment/cielo
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 4000:4000
    networks:
      - new
  transfeera:
    container_name: transfeera
    depends_on:
      - db
    build: 
          context: ./microservices/payment/transfeera
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
            - 3900:3900
    networks:
      - new
  dashboard:
    container_name: dashboard
    build: ./dashboard
    networks:
      - new
    ports:
      - 3500:3500
  nextjs:
    container_name: nextjs
    build: ./front-main
    ports:
      - 3000:3000
    networks:
      - new
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - new
networks:
  new:

